# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppSampleBinaryMatricesInterval <- function(rowsumsL, rowsumsU, colsumsL, colsumsU, N, steps, method) {
    .Call('_marathonR_CppSampleBinaryMatricesInterval', PACKAGE = 'marathonR', rowsumsL, rowsumsU, colsumsL, colsumsU, N, steps, method)
}

CppSampleBinaryMatricesFixed <- function(rowsums, colsums, N, steps, method) {
    .Call('_marathonR_CppSampleBinaryMatricesFixed', PACKAGE = 'marathonR', rowsums, colsums, N, steps, method)
}

CppIsRealizableInterval <- function(rowsumsL, rowsumsU, colsumsL, colsumsU) {
    .Call('_marathonR_CppIsRealizableInterval', PACKAGE = 'marathonR', rowsumsL, rowsumsU, colsumsL, colsumsU)
}

CppIsRealizableFixed <- function(rowsums, colsums) {
    .Call('_marathonR_CppIsRealizableFixed', PACKAGE = 'marathonR', rowsums, colsums)
}

